name: Release

on:
  pull_request:
    branches: [release]
  push:
    branches: [release]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️ Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📦 Install release-it globally
        run: bun i -g release-it @release-it/bumper @release-it/conventional-changelog

      - name: 🤖 Initialize Git User
        run: |
          git config --global user.email "detactive.app@gmail.com"
          git config --global user.name "[CI]"

      - name: 🏷️ Create GitHub Release
        run: bunx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}