name: Development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.1.3

      - name: 🔎 Run Lint
        run: deno fmt --check

      - name: 🧪 Run Test
        run: deno test
